name = "Cluster.jl"
uuid = "a199801d-da2f-495f-981e-bf842e0b3fa3"
authors = ["Mohamad Bassel Fatloun<fatloun@campus.tu-berlin.de>", "Viktor Lorentz<lorentz@campus.tu-berlin.de>", "Florentin Marquardt<marquardt@campus.tu-berlin.de>", "Omadbek Meliev<meliev@campus.tu-berlin.de>"]
version = "0.0.0"

[compat]
julia = "1.10"
