name = "Cluster"
uuid = "a199801d-da2f-495f-981e-bf842e0b3fa3"
authors = ["Mohamad Bassel Fatloun<fatloun@campus.tu-berlin.de>", "Viktor Lorentz<lorentz@campus.tu-berlin.de>", "Florentin Marquardt<marquardt@campus.tu-berlin.de>", "Omadbek Meliev<meliev@campus.tu-berlin.de>"]
version = "0.0.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CodecZlib = "944b1d66-785c-5afd-91f1-9de20f533193"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
GZip = "92fee26a-97fe-5a0c-ad85-20a5f3185b63"

[compat]
julia = "1.10"
